version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      pip-validated-batch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:05"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      docker-validated-batch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:10"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      actions-validated-batch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
